site_name: 'eks-golang543'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/prayankag/eks-golang543
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
