---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: golang434-quota
  namespace: golang434
  labels:
    kubernetes.io/metadata.name: golang434
    backstage.io/kubernetes-id: golang434
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
